#!/bin/bash
# Created by 097-026-7262
if [[ -e /etc/debian_version ]]; then
	OS=debian
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	RCLOCAL='/etc/rc.d/rc.local'
	chmod +x /etc/rc.d/rc.local
else
	echo "ดูเหมือนว่าคุณไม่ได้ใช้ตัวติดตั้งนี้ในระบบ Debian, Ubuntu หรือ CentOS "
	exit
fi
clear
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'
echo -e "-------------------------------------------------------" | lolcat
	echo ""
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo -e "-------------------------------------------------------" | lolcat
	echo -e ">>>>>> [ WWW.FACEBOOK.COM / CEOLNW 097-026-7262 ] <<<<<" | lolcat
	echo -e "-------------------------------------------------------" | lolcat
	echo -e ""
	echo -e "|||||||||||||| เกี่ยวกับการสร้างบัญชี VPN SSH |||||||||||||||" | lolcat
	echo -e "-------------------------------------------------------" | lolcat
	echo -e " [+] |${color1}1${color3}. ${color3} สร้างบัญชี SSH & OpenVPN${color3}"
	echo -e " [+] |${color1}2${color3}. ${color3} สร้างบัญชีแบบสุ่ม SSH/OpenVPN${color3}"
	echo -e " [+] |${color1}3${color3}. ${color3} สร้างบัญชีทดลอง SSH & OpenVPN${color3}"
	echo -e " [+] |${color1}4${color3}. ${color3} เพิ่มเวลาที่ใช้งานของบัญชี SSH & OpenVPN${color3}"
	echo -e " [+] |${color1}5${color3}. ${color3} เปลี่ยนรหัสผ่านบัญชี SSH/OpenVPN${color3}"
	echo -e " [+] |${color1}6${color3}. ${color3} ลบบัญชี SSH & OpenVPN${color3}"
	echo -e "-------------------------------------------------------" | lolcat
	echo -e "||||||||||||||| เกี่ยวกับการ Ban และเตะบัญชี |||||||||||||||" | lolcat
	echo -e "-------------------------------------------------------" | lolcat
	echo -e " [+] |${color1}7${color3}. ${color3} เตะบัญชีที่เชื่อมต่อเกินกำหนด${color3}"
	echo -e " [+] |${color1}8${color3}. ${color3} ดูรายชื่อผู้ใช้ที่ถูก Ban ${color3}"
	echo -e " [+] |${color1}9${color3}. ${color3} Ban บัญชีที่เชื่อมต่อเกินกำหนด${color3}"
	echo -e " [+] |${color1}10${color3}. ${color3}ยกเลิก Ban บัญชี SSH & OpenVPN${color3}"
	echo -e " [+] |${color1}11${color3}| ${color3}แสดงรายชื่อบัญชีทั้งหมด SSH & OpenVPN${color3}"
	echo -e "-------------------------------------------------------" | lolcat
	echo -e "||||||||||||||||||||| เกี่ยวกับ อื่น ๆ |||||||||||||||||||||" | lolcat
	echo -e "-------------------------------------------------------" | lolcat
	echo -e " [+] |${color1}39${color3}| ${color3}Speedtest${color3}"
	echo -e " [+] |${color1}40${color3}| ${color3}Benchmark${color3}"
	echo -e " [+] |${color1}41${color3}| ${color3}ดูการใช้ RAM ของเซิร์ฟเวอร์ ${color3}"
	echo -e " [+] |${color1}42${color3}| ${color3}เช็ค Bandwidth ที่ใช้ ${color3}"
	echo -e " [+] |${color1}43${color3}| ${color3}ดูรายละเอียดของการติดตั้งระบบ${color3}"
	#echo -e "${color1}38${color3}. ${color2}สร้างบัญชี Proxy${color3}"
	echo -e " [+] |${color1}44${color3}| ${color3}Update Script${color3}"
echo -e "-------------------------------------------------------" | lolcat
read -p " [>] เลือกคำสั่งที่ต้องการ (พิมพ์เลข): " x
echo -e "-------------------------------------------------------" | lolcat
if test $x -eq 1; then
user-add
elif test $x -eq 2; then
user-generate
elif test $x -eq 3; then
user-trial
elif test $x -eq 4; then
user-addday
elif test $x -eq 5; then
user-password
elif test $x -eq 6; then
user-delete
elif test $x -eq 7; then
read -p " [>] ตั้งการจำกัดการเชื่อมต่อ พิมพ์ (1-2): " MULTILOGIN
user-limit $MULTILOGIN
elif test $x -eq 8; then
log-ban
elif test $x -eq 9; then
read -p " [>] ตั้งการจำกัดการเชื่อมต่อ พิมพ์ (1-2): " MULTILOGIN
user-ban $MULTILOGIN
elif test $x -eq 10; then
user-unban
elif test $x -eq 11; then
user-list
elif test $x -eq 39; then
speedtest --share
elif test $x -eq 40; then
bench-network
elif test $x -eq 41; then
ram
elif test $x -eq 42; then
vnstat
elif test $x -eq 43; then
log-install
elif test $x -eq 44; then
echo ""
echo " [>] ติดตามได้ที่ www.facebook.com/ceolnw"
elif test $x -eq ""; then
clear
echo ""
echo " [!] สคริปต์นี้จะทำงานโดยอัตโนมัติทุกๆ 12 ชั่วโมง"
echo " [>] คุณไม่จำเป็นต้องเรียกใช้ด้วยตนเอง"
sleep 10
user-expire
else
echo "ไม่พบตัวเลือกในเมนู."
exit
fi
