#!/bin/bash
# Created by http://www.เฮียเบิร์ด.com
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to script.เฮียเบิร์ด.com..."
sleep 0.2
echo "Checking Permision..."
sleep 0.3
# GO TO ROOT
MYIP=$(wget -qO- ipv4.icanhazip.com);
myip=$(wget -qO- ipv4.icanhazip.com);

flag=0
	
#iplist="ip.txt"

wget --quiet -O iplist.txt http://xn--l3clxf6cwbe0gd7j.com/iplist.txt

#if [ -f iplist ]
#then

iplist="iplist.txt"

lines=`cat $iplist`
#echo $lines

for line in $lines; do
#        echo "$line"
        if [ "$line" = "$myip" ];
        then
                flag=1
        fi

done

if [ $flag -eq 0 ]
then
   echo  "ขออภัยเฉพาะ IP @ Password ที่ลงทะเบียนเท่านั้นที่สามารถใช้สคริปต์นี้ได้!
ติดต่อ: HERE BIRD (097-026-7262) Facebook : m.me/ceolnw" | lolcat
	exit 1
sleep 1
clear
fi
read -p "Username : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo "UserName มีแล้ว"
exit 0
else
read -p "Password : " password
read -p "Server use (Day):" masa_aktif
MYIP=$(wget -qO- ipv4.icanhazip.com)
today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
clear
echo "Connecting to script.เฮียเบิร์ด.com..."
sleep 0.4
echo "Creating Account..."
sleep 0.3
echo "Generating Host..."
sleep 0.2
echo "Creating Your New Username: $username"
sleep 0.2
echo "Creating Password for $username"
sleep 1


useradd $username
usermod -s /bin/false $username
usermod -e  $tanggal_expired $username
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo -e ""
echo -e ""
echo -e ""
echo -e ""| lolcat
echo -e "|       New Account Information SSH      |" | boxes -d dog | lolcat
echo -e "============[[-SERVER-PREMIUM-]]===========" | lolcat
echo -e "     Host       : $MYIP" | lolcat
echo -e "     Username      : $username" | lolcat
echo -e "     Password      : $password                   " | lolcat
echo -e "     Port Dropbear: 443,80         " | lolcat
echo -e "     Port OpenSSH : 22,143         " | lolcat
echo -e "     Port Squid   : 8080,3128      " | lolcat
echo -e "     Server Day      : $masa_aktif Day" | lolcat
echo -e "     Warning       : Max 2 login          " | lolcat
echo -e "-------------------------------------------" | lolcat
echo -e "     Exp.   : $tanggal_expired_display" | lolcat
echo -e "===========================================" | lolcat
echo -e "   Admin & Detail  :                      "| lolcat
echo -e "   HACKING-DDOS-PHISING-SPAM-TORENT       " | lolcat
echo -e "   HEREBIRD & OCSPANEL.INFO               "| lolcat
echo -e "   Script by 097-026-7262                 "| lolcat
echo -e "===========================================" | lolcat
echo -e "   Config VPN:                            "| lolcat
echo -e "   http://$MYIP/client.ovpn        " | lolcat
echo -e "-------------------------------------------" | lolcat
echo -e ""
echo -e ""
fi
