#!/bin/bash
# Created by http://www.เฮียเบิร์ด.com
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to script.เฮียเบิร์ด.com..."
sleep 0.2
echo "Checking Permision..."
sleep 0.3
# GO TO ROOT
MYIP=$(wget -qO- ipv4.icanhazip.com);
myip=$(wget -qO- ipv4.icanhazip.com);

flag=0
	
#iplist="ip.txt"

wget --quiet -O iplist.txt http://xn--l3clxf6cwbe0gd7j.com/iplist.txt

#if [ -f iplist ]
#then

iplist="iplist.txt"

lines=`cat $iplist`
#echo $lines

for line in $lines; do
#        echo "$line"
        if [ "$line" = "$myip" ];
        then
                flag=1
        fi

done

if [ $flag -eq 0 ]
then
   echo  "ขออภัยเฉพาะ IP @ Password ที่ลงทะเบียนเท่านั้นที่สามารถใช้สคริปต์นี้ได้!
ติดต่อ: HERE BIRD (097-026-7262) Facebook : m.me/ceolnw" | lolcat
	exit 1
sleep 1
clear
fi
read -p "ใส่ชื่อบัญชีที่จะเพิ่มวัน: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "ป้อนระยะเวลาใช้งานบัญชีเพิ่มเติมตั้งแต่วันนี้ (วัน): " masa_aktif

today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
clear
echo "Connecting to script.เฮียเบิร์ด.com..."
sleep 0.5
echo "กำลังดำเนินการ..."
sleep 0.5
passwd -u $username
usermod -e  $tanggal_expired $username
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
clear
echo -e ""
echo -e ""
echo -e ""
echo -e ""| lolcat
echo -e "|        ACCOUNT INFORMATION SSH      |" | boxes -d dog | lolcat
echo -e "============[[-SERVER-PREMIUM-]]===========" | lolcat
echo -e "     Username      : $username" | lolcat
echo -e "     Server Day      : $masa_aktif Day" | lolcat
echo -e "    Exp. : $tanggal_expired_display" | lolcat
echo -e "-------------------------------------------" | lolcat
echo -e "===========================================" | lolcat
echo -e "   Admin & Detail  :                      "| lolcat
echo -e "   HACKING-DDOS-PHISING-SPAM-TORENT       " | lolcat
echo -e "   HEREBIRD & OCSPANEL.INFO               "| lolcat
echo -e "   Script by 097-026-7262                 "| lolcat
echo -e "===========================================" | lolcat
echo -e "-------------------------------------------" | lolcat
echo -e ""
echo -e ""
fi
