#!/bin/bash
# Created by http://www.เฮียเบิร์ด.com
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to script.เฮียเบิร์ด.com..."
sleep 0.2
echo "Checking Permision..."
sleep 0.3
# GO TO ROOT
MYIP=$(wget -qO- ipv4.icanhazip.com);
myip=$(wget -qO- ipv4.icanhazip.com);

flag=0
	
#iplist="ip.txt"

wget --quiet -O iplist.txt http://xn--l3clxf6cwbe0gd7j.com/iplist.txt

#if [ -f iplist ]
#then

iplist="iplist.txt"

lines=`cat $iplist`
#echo $lines

for line in $lines; do
#        echo "$line"
        if [ "$line" = "$myip" ];
        then
                flag=1
        fi

done

if [ $flag -eq 0 ]
then
   echo  "ขออภัยเฉพาะ IP @ Password ที่ลงทะเบียนเท่านั้นที่สามารถใช้สคริปต์นี้ได้!
ติดต่อ: HERE BIRD (097-026-7262) Facebook : m.me/ceolnw" | lolcat
	exit 1
sleep 1
clear
fi

if [[ $USER != 'root' ]]; then
	echo "ขออภัยคุณต้องเรียกใช้งานนี้เป็น root"
	exit
fi

# get the VPS IP
MYIP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;

if [ "$MYIP" = "" ]; then
	MYIP=$(wget -qO- ipv4.icanhazip.com)
fi

echo -e ""| lolcat
echo -e "==========[[-SERVER-PREMIUM-]]=========" | lolcat
echo -e " รายชื่อ ทั้งหมด " | lolcat
echo -e "=================[[]]================" | lolcat
echo -e "USERNAME              EXP DATE     " | lolcat
echo -e "=================[[]]================" | lolcat

while read expired
do
	AKUN="$(echo $expired | cut -d: -f1)"
	ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
	exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
	if [[ $ID -ge 1000 ]]; then
		printf "%-21s %2s\n" "$AKUN" "$exp"
	fi
done < /etc/passwd

JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"

echo -e "=================[[]]================" | lolcat
echo -e "ทั้งหมด : $JUMLAH user" | lolcat
echo -e "=================[[]]================" | lolcat
echo -e ""
echo -e "=================[[]]================" | lolcat

echo -e "===========================================" | lolcat
echo -e "   Admin & Detail  :                       "| lolcat
echo -e "   HACKING-DDOS-PHISING-SPAM-TORENT        " | lolcat
echo -e "   HEREBIRD & OCSPANEL.INFO                "| lolcat
echo -e "   Script by 097-026-7262                  "| lolcat
echo -e "===========================================" | lolcat
echo -e " "| lolcat
